In [17]:
from pathlib import Path
import sys

project_root = Path.cwd().resolve()
if project_root.name == "notebooks":
    project_root = project_root.parent

if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

import pandas as pd
from app.ingestion.loader import add_ids, clean_house_size, filter_columns

In [18]:
pd1 = pd.read_csv("../data/raw/Indian_housing_Mumbai_data.csv")
pd2 = pd.read_csv("../data/raw/Indian_housing_Pune_data.csv")
pd3 = pd.read_csv("../data/raw/Indian_housing_Delhi_data.csv")

pd1.head()

,house_type,house_size,location,city,latitude,longitude,price,currency,numBathrooms,numBalconies,isNegotiable,priceSqFt,verificationDate,description,SecurityDeposit,Status
0,2 BHK Apartment,"1,180 sq ft",Ulwe,Mumbai,18.971046,73.017723,19000,INR,2.0,NaN,NaN,NaN,Posted 2 years ago,It has area of 1180 sqft and is available at a...,No Deposit,Furnished
1,2 BHK Apartment,"1,120 sq ft",Ulwe,Mumbai,18.966377,73.012802,12500,INR,2.0,NaN,NaN,NaN,Posted 2 years ago,Well designed 2 bhk multistorey apartment is a...,No Deposit,Unfurnished
2,2 BHK Apartment,"1,200 sq ft",Panvel,Mumbai,18.965979,73.124649,22000,INR,2.0,NaN,NaN,NaN,Posted a month ago,A spacious 2 bhk multistorey apartment is avai...,No Deposit,Unfurnished
3,2 BHK Apartment,750 sq ft,Kandivali West,Mumbai,19.213598,72.833633,28500,INR,2.0,NaN,NaN,NaN,Posted 3 years ago,It has a built-up area of 750 sqft and is avai...,No Deposit,Unfurnished
4,3 BHK Apartment,"1,400 sq ft",Chembur,Mumbai,19.062933,72.892395,50000,INR,3.0,NaN,NaN,NaN,Posted 3 years ago,The house is semi-furnished. It has power back...,No Deposit,Semi-Furnished

In [19]:
print(pd1.info())
print("=" * 20)
pd1["house_type"].value_counts().head()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   house_type        5000 non-null   str
 1   house_size        5000 non-null   str
 2   location          5000 non-null   str
 3   city              5000 non-null   str
 4   latitude          5000 non-null   float64
 5   longitude         5000 non-null   float64
 6   price             5000 non-null   int64
 7   currency          5000 non-null   str
 8   numBathrooms      4986 non-null   float64
 9   numBalconies      733 non-null    float64
 10  isNegotiable      571 non-null    str
 11  priceSqFt         0 non-null      float64
 12  verificationDate  5000 non-null   str
 13  description       4922 non-null   str
 14  SecurityDeposit   5000 non-null   str
 15  Status            5000 non-null   str
dtypes: float64(5), int64(1), str(10)
memory usage: 625.1 KB
None
====================

house_type
2 BHK Apartment           2150
1 BHK Apartment           1580
3 BHK Apartment            896
1 RK Studio Apartment      168
4 BHK Apartment            133
Name: count, dtype: int64

In [20]:
print(pd2.info())
print("=" * 20)
pd1["house_type"].value_counts().head()

<class 'pandas.DataFrame'>
RangeIndex: 3910 entries, 0 to 3909
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   house_type        3910 non-null   str
 1   house_size        3910 non-null   str
 2   location          3910 non-null   str
 3   city              3910 non-null   str
 4   latitude          3910 non-null   float64
 5   longitude         3910 non-null   float64
 6   price             3910 non-null   int64
 7   currency          3910 non-null   str
 8   numBathrooms      3893 non-null   float64
 9   numBalconies      1821 non-null   float64
 10  isNegotiable      526 non-null    str
 11  priceSqFt         0 non-null      float64
 12  verificationDate  3910 non-null   str
 13  description       3442 non-null   str
 14  SecurityDeposit   3910 non-null   str
 15  Status            3910 non-null   str
dtypes: float64(5), int64(1), str(10)
memory usage: 488.9 KB
None
====================

house_type
2 BHK Apartment           2150
1 BHK Apartment           1580
3 BHK Apartment            896
1 RK Studio Apartment      168
4 BHK Apartment            133
Name: count, dtype: int64

In [21]:
print(pd3.info())
print("=" * 20)
pd1["house_type"].value_counts().head()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   house_type        5000 non-null   str
 1   house_size        5000 non-null   str
 2   location          5000 non-null   str
 3   city              5000 non-null   str
 4   latitude          5000 non-null   float64
 5   longitude         5000 non-null   float64
 6   price             5000 non-null   int64
 7   currency          5000 non-null   str
 8   numBathrooms      4975 non-null   float64
 9   numBalconies      2737 non-null   float64
 10  isNegotiable      179 non-null    str
 11  priceSqFt         0 non-null      float64
 12  verificationDate  5000 non-null   str
 13  description       4715 non-null   str
 14  SecurityDeposit   5000 non-null   str
 15  Status            5000 non-null   str
dtypes: float64(5), int64(1), str(10)
memory usage: 625.1 KB
None
====================

house_type
2 BHK Apartment           2150
1 BHK Apartment           1580
3 BHK Apartment            896
1 RK Studio Apartment      168
4 BHK Apartment            133
Name: count, dtype: int64

In [22]:
clean_house_size("1,180 sq ft")
clean_house_size("450 sq ft")
clean_house_size("1,90,000 sq ft")

190000.0

In [23]:
clean_house_size("450 sq ft")
clean_house_size("1,90,000 sq ft")

190000.0

In [24]:
test_df = add_ids(pd1.copy(), "Pune")
test_df[["id"]].head()

       id
0  Pune_0
1  Pune_1
2  Pune_2
3  Pune_3
4  Pune_4

In [25]:
filtered = filter_columns(pd1.copy())
filtered.head()

,house_type,house_size,location,city,price,numBathrooms,description,SecurityDeposit,Status
0,2 BHK Apartment,"1,180 sq ft",Ulwe,Mumbai,19000,2.0,It has area of 1180 sqft and is available at a...,No Deposit,Furnished
1,2 BHK Apartment,"1,120 sq ft",Ulwe,Mumbai,12500,2.0,Well designed 2 bhk multistorey apartment is a...,No Deposit,Unfurnished
2,2 BHK Apartment,"1,200 sq ft",Panvel,Mumbai,22000,2.0,A spacious 2 bhk multistorey apartment is avai...,No Deposit,Unfurnished
3,2 BHK Apartment,750 sq ft,Kandivali West,Mumbai,28500,2.0,It has a built-up area of 750 sqft and is avai...,No Deposit,Unfurnished
4,3 BHK Apartment,"1,400 sq ft",Chembur,Mumbai,50000,3.0,The house is semi-furnished. It has power back...,No Deposit,Semi-Furnished