# 🧹 Data Preprocessing

## Objective

Prepare the dataset for Machine Learning by:

- Removing duplicate records
- Separating features and target
- Handling categorical variables
- Splitting training and testing data

In [39]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [40]:
df = pd.read_csv("../data/raw/House_Price_Data.csv")

df.head()

   bhk propertytype   location   sqft  pricepersqft  totalprice
0    3         Flat  Ahmedabad   1346          6233    15700000
1    4         Flat  Ahmedabad   1872          4873    17500000
2    4         Flat  Ahmedabad   1650          6733    20200000
3    5         Flat  Ahmedabad  10201          8499    86700000
4    3         Flat  Ahmedabad    968          5944    10400000

In [41]:
df.shape

(14119, 6)

In [42]:
df.duplicated().value_counts()

False    14027
True        92
Name: count, dtype: int64

Check the dataset size before preprocessing.

In [43]:
df = df.drop_duplicates()

df.shape

(14027, 6)

In [44]:
df = df.drop(columns=["pricepersqft"])

df.columns

Index(['bhk', 'propertytype', 'location', 'sqft', 'totalprice'], dtype='str')

The `pricepersqft` feature is excluded because it is directly related to the target (`totalprice`) and may introduce data leakage.

In [45]:
x = df.drop(columns=["totalprice"])

y = df["totalprice"]

In [46]:
x.head()

   bhk propertytype   location   sqft
0    3         Flat  Ahmedabad   1346
1    4         Flat  Ahmedabad   1872
2    4         Flat  Ahmedabad   1650
3    5         Flat  Ahmedabad  10201
4    3         Flat  Ahmedabad    968

In [47]:
y.head()

0    15700000
1    17500000
2    20200000
3    86700000
4    10400000
Name: totalprice, dtype: int64

In [48]:
categorical_features = ["propertytype", "location"]

numerical_features = ["bhk", "sqft"]

Numerical and categorical features require different preprocessing techniques.

In [49]:
preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features,
        )
    ],
    remainder="passthrough",
)

In [50]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [51]:
print("Training Features :", X_train.shape)
print("Testing Features  :", X_test.shape)
print("Training Labels   :", y_train.shape)
print("Testing Labels    :", y_test.shape)

Training Features : (11221, 4)
Testing Features  : (2806, 4)
Training Labels   : (11221,)
Testing Labels    : (2806,)

The dataset has been split into 80% training data and 20% testing data.

In [ ]:
X_train_processed = preprocessor.fit_transform(X_train)     # Apply Preprocessing

X_test_processed = preprocessor.transform(X_test)