# 📊 Model Evaluation

## Objective

Evaluate the performance of the Linear Regression model using regression metrics.

In [1]:
import joblib
import pandas as pd

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score,
)

In [2]:
model = joblib.load(
    "../models/trained_models/linear_regression.pkl"
)

In [3]:
df = pd.read_csv("../data/processed/House_Price_Data_cleaned.csv")

In [4]:
X = df.drop(columns=["totalprice"])

y = df["totalprice"]

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
)

In [6]:
preprocessor = joblib.load(
    "../models/preprocessors/preprocessor.pkl"
)

X_train = preprocessor.fit_transform(X_train)

X_test = preprocessor.transform(X_test)

In [7]:
predictions = model.predict(X_test)

In [8]:
mae = mean_absolute_error(
    y_test,
    predictions
)

print(mae)

6693226.6371304495

In [9]:
mse = mean_squared_error(
    y_test,
    predictions,
)

print(mse)

327140765716910.6

In [10]:
rmse = mse ** 0.5

print(rmse)

18087033.082208663

In [11]:
r2 = r2_score(
    y_test,
    predictions,
)

print(r2)

0.2358649982940484

In [12]:
print(f"MAE : {mae:.2f}")

print(f"MSE : {mse:.2f}")

print(f"RMSE: {rmse:.2f}")

print(f"R²  : {r2:.4f}")

MAE : 6693226.64
MSE : 327140765716910.62
RMSE: 18087033.08
R²  : 0.2359

In [13]:
results = pd.DataFrame(
    {
        "Actual": y_test.values,
        "Predicted": predictions,
    }
)

results.head(15)

      Actual     Predicted
0    6220000 -3.073473e+05
1    1400000 -6.518295e+05
2   14000000  1.385343e+07
3   18000000  3.098782e+07
4    3000000  4.198210e+06
5    9560000  3.601393e+06
6   12900000  1.467973e+07
7    8000000  1.521995e+07
8    3800000  7.475026e+06
9   23200000  1.479863e+07
10  30000000  1.074388e+07
11   6500000  1.039628e+07
12   5740000  2.791425e+05
13  27700000  2.906292e+07
14   4500000  1.016996e+07

In [14]:
results["Error"] = (
    results["Actual"]
    - results["Predicted"]
)

results.head(15)

      Actual     Predicted         Error
0    6220000 -3.073473e+05  6.527347e+06
1    1400000 -6.518295e+05  2.051829e+06
2   14000000  1.385343e+07  1.465721e+05
3   18000000  3.098782e+07 -1.298782e+07
4    3000000  4.198210e+06 -1.198210e+06
5    9560000  3.601393e+06  5.958607e+06
6   12900000  1.467973e+07 -1.779727e+06
7    8000000  1.521995e+07 -7.219947e+06
8    3800000  7.475026e+06 -3.675026e+06
9   23200000  1.479863e+07  8.401366e+06
10  30000000  1.074388e+07  1.925612e+07
11   6500000  1.039628e+07 -3.896280e+06
12   5740000  2.791425e+05  5.460858e+06
13  27700000  2.906292e+07 -1.362921e+06
14   4500000  1.016996e+07 -5.669959e+06

# Summary

Model evaluation completed using

- Mean Absolute Error
- Mean Squared Error
- Root Mean Squared Error
- R² Score

These metrics provide a quantitative assessment of the regression model's performance.