# 📊 Model Comparison

## Objective

Compare multiple regression models using the same dataset,
preprocessing pipeline, and evaluation metrics.

Models

- Linear Regression
- Decision Tree Regressor
- Random Forest Regressor

In [11]:
import joblib
import pandas as pd

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score,
)

In [12]:
df = pd.read_csv("../data/processed/House_Price_Data_cleaned.csv")

df.head()

   bhk propertytype   location   sqft  totalprice
0    3         Flat  Ahmedabad   1346    15700000
1    4         Flat  Ahmedabad   1872    17500000
2    4         Flat  Ahmedabad   1650    20200000
3    5         Flat  Ahmedabad  10201    86700000
4    3         Flat  Ahmedabad    968    10400000

In [13]:
X = df.drop(columns=["totalprice"])

y = df["totalprice"]

In [14]:
categorical_features = [
    "propertytype",
    "location",
]

categorical_transformer = OneHotEncoder(
    handle_unknown="ignore"
)

preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            categorical_transformer,
            categorical_features,
        )
    ],
    remainder="passthrough",
)

In [15]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
)

In [16]:
X_train = preprocessor.fit_transform(X_train)

X_test = preprocessor.transform(X_test)

In [17]:
models = {
    "Linear Regression": LinearRegression(),
    "Decision Tree": DecisionTreeRegressor(
        random_state=42
    ),
    "Random Forest": RandomForestRegressor(
        random_state=42
    ),
}

In [18]:
def evaluate_model(model):

    model.fit(X_train, y_train)

    predictions = model.predict(X_test)

    mae = mean_absolute_error(
        y_test,
        predictions,
    )

    mse = mean_squared_error(
        y_test,
        predictions,
    )

    rmse = mse ** 0.5

    r2 = r2_score(
        y_test,
        predictions,
    )

    return [
        mae,
        rmse,
        r2,
    ]

In [19]:
results = []

for name, model in models.items():

    scores = evaluate_model(model)

    results.append(
        [name] + scores
    )

In [20]:
comparison = pd.DataFrame(
    results,
    columns=[
        "Model",
        "MAE",
        "RMSE",
        "R²",
    ],
)

comparison

               Model           MAE          RMSE        R²
0  Linear Regression  6.693227e+06  1.808703e+07  0.235865
1      Decision Tree  6.170614e+06  2.467949e+07 -0.422682
2      Random Forest  5.243603e+06  1.881941e+07  0.172729

In [21]:
comparison.sort_values(
    by="R²",
    ascending=False,
)

               Model           MAE          RMSE        R²
0  Linear Regression  6.693227e+06  1.808703e+07  0.235865
2      Random Forest  5.243603e+06  1.881941e+07  0.172729
1      Decision Tree  6.170614e+06  2.467949e+07 -0.422682

# Engineering Notes

## Decisions

- Compared three regression models using identical preprocessing.
- Used the same train/test split for a fair comparison.

## Limitations

- Duplicate feature leakage has not yet been fixed.
- Outlier handling has not yet been implemented.
- Hyperparameter tuning has not been performed.
- Pipeline artifact has not yet been created.

## Next Steps

- Select the best-performing model.
- Begin the Engineering Refactor phase.